### PR TITLE
Update packages and PHP version

### PR DESCRIPTION
**Pull request by SuperDJ**
|    Q          |   A
|-------------- | ------
| Documentation |no
| Bugfix        | no
| BC Break      |no
| New Feature   |no
| RFC           | no
| QA            | no

### CODE REVIEW

**Comment by froschdesign** [comment]
@SuperDJ 
Thanks for you help!

Please check the failing checks: https://github.com/laminas/laminas-xml/actions/runs/11233189933/job/31226396126?pr=18
But switching to a new version of laminas-coding-standard is guaranteed to lead to further problems.

**Comment by SuperDJ** [comment]
@froschdesign could you elaborate on the further problems? 

As only php 8.1 appears to fails, could we already consider dropping support for it? I'm aware of the [PHP lifecycle](https://www.php.net/supported-versions.php) not dropping support for 8.1 yet.

**Comment by froschdesign** [comment]
> As only php 8.1 appears to fails, could we already consider dropping support for it? I'm aware of the [PHP lifecycle](https://www.php.net/supported-versions.php) not dropping support for 8.1 yet.

This will not help, because the problem is not the PHP version, but that there are new rules for code styling.
If the problem with the XML file is solved, then there will also be a result for the coding standard:

```bash
phpcs.xml validates
<?xml version="1.0"?>
<ruleset name="Laminas coding standard">
    <rule ref="./vendor/laminas/laminas-coding-standard/ruleset.xml"/>

    <!-- Paths to check -->
    <file>src</file>
    <file>test</file>
</ruleset>
Running ./vendor/bin/phpcs -q --report=checkstyle | cs2pr
Error: Start tag expected, '<' not found on line 1, column 1

ERROR: Referenced sniff "./vendor/laminas/laminas-coding-standard/ruleset.xml" does not exist
```
https://github.com/laminas/laminas-xml/actions/runs/11233189933/job/31226396126?pr=18

**Comment by froschdesign** [comment]
I have another suggestion: Update only the PHP version and undo all other changes.

**Comment by SuperDJ** [comment]
@froschdesign I know that is possible. But I think it would be nice to get rid of [laminas/laminas-zendframework-bridge](https://packagist.org/packages/laminas/laminas-zendframework-bridge)

**Comment by froschdesign** [comment]
In your own applications you can already remove the bridge via Composer configuration file:

```json
    "replace": {
        "laminas/laminas-zendframework-bridge": "*"
    },
```

https://getcomposer.org/doc/04-schema.md#replace

**Comment by Ocramius** [comment]
> @froschdesign I know that is possible. But I think it would be nice to get rid of [laminas/laminas-zendframework-bridge](https://packagist.org/packages/laminas/laminas-zendframework-bridge)

see other patches that we've done on that front: we explicitly conflict with the `zendframework/` variant of the component, when doing so, so we avoid installation in apps that still rely on the bridge.

**Comment by SuperDJ** [comment]
Closed in favor of https://github.com/laminas/laminas-xml/pull/19

**Pull request closed without merging**
